replicaCount: 2

env:
  database: "off" # prefer DB-less for simpler setup; for HA use Postgres

proxy:
  enabled: true
  type: ClusterIP

ingressController:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
